### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by ShuvenduRoy** [huawei-noah/CV-Backbones#78]
Hi,

I am having the following issue that occurs with Pyramid TNT models but not with TNT models.

`
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [2, 128, 32, 32]], which is output 0 of ReluBackward0, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
`

**Comment by iamhankai** [comment]
Thanks. I've fixed it: 1a98c857e0569f7405f7eec4b40b17eea02914cb

**Comment by ShuvenduRoy** [comment]
Hi. I tried the fix. However, I am still getting the error in the same block of code.

**Comment by iamhankai** [comment]
The inplace operation is fixed: https://github.com/huawei-noah/CV-Backbones/commit/e560a122da3e4c4f1aaf25e8960989ebada11422

**Comment by ShuvenduRoy** [comment]
It worked. Thanks. 

I was wondering, is this in place operation error caused by the latest version of Pytorch?

Bdw, there is a mistake in the readme.md file. The is not model named 'ptnt_s_patch16_224'. There is one for 256 dim.
